// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vgwgeuwptjpcvkpnqgsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZnd2dldXdwdGpwY3ZrcG5xZ3NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxNDIyODksImV4cCI6MjA2ODcxODI4OX0.PHZSGiolNWny45a54_Amo-ZVsO79bXnWa1_In7tvDC8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});